matrix:
  include:
    - language: python
      python: "3.6"
      before_install:
        - cd sparcs09-api/
      install:
        - pip install -r requirements.txt
      script:
        - flake8 .
    - language: node_js
      node_js: "6"
      before_install:
        - cd sparcs09-web/
      install:
        - npm install
      script:
        - npm run lint
notifications:
  email: false
